# Use official MySQL image
FROM mysql:8.0

# Set environment variables (adjust as needed)
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=lab3_2Cars
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Expose MySQL port
EXPOSE 3306